name: Citrix Enterprise Browser LTSR test
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    paths:
      - 'Citrix-Enterprise-Browser-LTSR/**'

jobs:
  Test-CEB-LTSR-Package:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: 🦺 Install validation extension
        run: choco install chocolatey-community-validation.extension -y
      - name: 📦 Pack Chocolatey Package
        run: choco pack Citrix-Enterprise-Browser-LTSR/Citrix-Enterprise-Browser-LTSR.nuspec
      - name: 🚀 Install Chocolatey Package
        run: choco install citrix-enterprise-browser-ltsr -y --debug --verbose --source "'.;https://community.chocolatey.org/api/v2/'"