name: xcp-ng-center test
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    paths:
      - 'xcp-ng-center/**'

jobs:
  Test-xenadmin-Package:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: 🦺 Install validation extension
        run: choco install chocolatey-community-validation.extension -y
      - name: 📦 Pack Chocolatey Package
        run: choco pack xcp-ng-center/xcp-ng-center.nuspec
      - name: 🚀 Install Chocolatey Package
        run: choco install xcp-ng-center -y --debug --verbose --source "'.;https://community.chocolatey.org/api/v2/'"